### ISSUE TITLE
SC Auto Rate Change

### ISSUE THREAD

**Issue by nkukral** [gobranch/rate_changes#14]
Updating Base Rates and Affinity Table 
Effective 10/1/2022 new business and 11/10/2022 renewal business

[SC PPA DS.11 - Affinity Discount Table.pdf](https://github.com/gobranch/rate_changes/files/9559669/SC.PPA.DS.11.-.Affinity.Discount.Table.pdf)
[SC PPA RP.1 - Base Rate Table.pdf](https://github.com/gobranch/rate_changes/files/9559670/SC.PPA.RP.1.-.Base.Rate.Table.pdf)

**Comment by matt-hewitt1** [comment]
Hi @nkukral! While it doesn't hurt to include the affinity discount changes here, these are defined outside of the ClarionDoor rater. There is a separate process (I'm unfamiliar with the details) to alert the tech team of these changes so that the rater inputs are properly defined. I believe these are part of more general countrywide changes to the affinity discount partners/groups, so they may well already be handled properly, but I wanted to mention for full disclosure.

The base rate changes have been made and included in the most recent ClarionDoor production release. They will take effect for new business on 10/1/2022 with no further action.

Closing this ticket now. Please reopen if there are changes due to objections.

**Comment by eperlman** [comment]
@rcraytonB please test and validate
